project:
  type: website
  output-dir: docs

website:
  title: "Francisco Letelier C"
  description: "Ciencia de datos, estadística y visualización"
  site-url: "https://franciscoletelier.github.io/demosite/"
  favicon: images/favicon.png
  open-graph: true
  twitter-card: true
  navbar:
    background: dark
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
      - href: proyectos.qmd
        text: Proyectos
      - href: about.qmd
        text: Sobre mí
    right:
      - icon: github
        href: https://franciscoletelier.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/francisco-letelier-castro/

  page-footer:
    left: "© 2026 Francisco Letelier C"
    right:
      - icon: github
        href: https://franciscoletelier.github.io
      - icon: envelope
        href: mailto:fletelierc@uft.edu


format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    smooth-scroll: true
    fontsize: 1.05em
    linkcolor: "#7c3aed"

editor: visual

