project:
  type: website
  output-dir: docs
  resources:
    - posts/*.html
    
website:
  title: "Francisco Letelier C"
  description: "Ciencia de datos, estadística y visualización"
  site-url: "https://franciscoletelier.github.io/demosite/"
  favicon: images/favicon.png
  open-graph: true
  twitter-card: true
  navbar:
    background: "#ffffff"
    pinned: true
#    background: dark
    left:
    - href: index.qmd
      text: Home
    - href: posts.qmd
      text: Artículos
    - href: about.qmd
      text: Sobre mi
    right:
      - icon: github
        href: https://franciscoletelier.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/francisco-letelier-castro/

  page-footer:
    left: "© 2026 Francisco Letelier C"
    right:
      - icon: github
        href: https://franciscoletelier.github.io
      - icon: envelope
        href: mailto:fletelierc@uft.edu


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    mainfont: "Inter"
    fontsize: 1.05em
    include-in-header:
      - text: |
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


editor: visual

